const GET_LIBRO_ALL = 'GET_LIBRO_ALL';
const GET_LIBRO_NAME = 'GET_LIBRO_NAME';
const GET_LIBRO_DETAIL = 'GET_LIBRO_DETAIL';
const GET_CATEGORIAS_ALL = 'GET_CATEGORIAS_ALL';
const FILTER_BY_ORDER = 'FILTER_BY_ORDER';
const FILTER_BY_CATEGORIAS = 'FILTER_BY_CATEGORIAS';
const FILTER_BY_CREATE = 'FILTER_BY_CREATE';
const CREATE_LIBRO = 'CREATE_LIBRO';
const CLEAR_ALL = 'CLEAR_ALL';

module.exports = {
    GET_LIBRO_ALL,
    GET_LIBRO_NAME,
    GET_LIBRO_DETAIL,
    GET_CATEGORIAS_ALL,
    FILTER_BY_ORDER,
    FILTER_BY_CATEGORIAS,
    FILTER_BY_CREATE,
    CREATE_LIBRO,
    CLEAR_ALL,
}